トップページのフッターの実装
KeiMichell/FreeMa pull request #14
Opened 2020-09-20 12:40 UTC by chomchompanic

＃What
トップページのフッターの実装

＃Why
各項目をクリックすることでユーザーが任意のページにアクセスできるようにするため。

2020-09-20 12:42 UTC, chomchompanic commented
https://gyazo.com/119045587e362a6ecc32f04ba03ddae0

フッターのスクショです

2020-09-21 00:11 UTC, shi0280 commented
見た目バッチリです！

2020-09-21 00:28 UTC, shi0280 commented on app/views/items/_footer.html.haml
> +
link_toにできたらそっちの方がいいかもしれません

2020-09-21 00:28 UTC, shi0280 commented on app/views/items/_footer.html.haml
> +        ヘルプ＆ガイド
content__headクラスはdivタグではなくh２タグにしてはいかがでしょうか（文字なので）？

2020-09-21 00:28 UTC, shi0280 commented on app/assets/stylesheets/modules/footer.scss
> +
最後の２つの「}」のインデントが左な気がしますがいかがでしょう？

2020-09-22 02:29 UTC, chomchompanic commented on app/views/items/_footer.html.haml
> +
修正しました！

2020-09-22 02:57 UTC, KeiMichell requested changes

2020-09-22 02:57 UTC, KeiMitchell commented on app/views/items/_footer.html.haml
> +%a(href="#")
こちらはlink_toタグを使いましょう!

参考: https://master.tech-camp.in/curriculums/4254

2020-09-22 02:57 UTC, KeiMitchell commented on app/assets/stylesheets/modules/footer.scss
> +          a {
こちらもlink_toで!

2020-09-22 02:57 UTC, KeiMitchell commented on app/views/items/_footer.html.haml
> +    %img.purchaseBtn__icon{:src => "http://furima.tokyo/assets/icon_camera-968c5ebaa05319bf1e2ad7508f852dd712504a4d26a1930d8bd87ec03ebcc37a.svg"}
こちらもimage_tagの方がいいかもしれません!

2020-09-22 02:57 UTC, KeiMichell commented on app/assets/stylesheets/modules/footer.scss
> +      a {
こちらの.appBanner .inner_icon aセレクタは.appBanner .inner_icon a:first-childセレクタの前に配置した方がいいというエラーがRubocopから出てますね。
CSSの『後勝ち』の法則に従うとコードが理解しやすくなるという
no-descending-specificityというルールが存在するらしいです！
参考：https://lnly.hatenablog.com/entry/2018/12/27/201835#:~:text=no%2Ddescending%2Dspecificity%20%E3%83%AB%E3%83%BC%E3%83%AB%E3%81%AB%E3%82%88%E3%82%8B%E8%AD%A6%E5%91%8A&text=child%20%E3%81%AE%E6%96%87%E5%AD%97%E8%89%B2%E3%82%92,%E3%82%B3%E3%83%B3%E3%83%91%E3%82%A4%E3%83%AB%E3%81%99%E3%82%8B%E3%81%A8%E3%81%93%E3%81%86%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82

2020-09-22 04:11 UTC, shi0280 commented
私の方はLGTMです

2020-09-23 08:18 UTC, chomchompanic commented
プルリクエスト出しました。レビューお願いします。

2020-09-23 11:17 UTC, KeiMichell commented
LGTMだと思います！！

2020-09-23 15:30 UTC, merged